name: ui-tests

on: [push, pull_request]

jobs:
  wp:
    runs-on: ubuntu-latest
    services:
      db: # wordpress db
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: somewordpress
          MYSQL_DATABASE: wordpress
          MYSQL_USER: wordpress
          MYSQL_PASSWORD: wordpress
        volumes:
          - db_data:/var/lib/mysql

      wordpress: # wordpress site
        image: wordpress:latest
        env:
          WORDPRESS_DB_HOST: db:3306
          WORDPRESS_DB_NAME: wordpress
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DEBUG: 1
        volumes:
          - wp_data:/var/www/html
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - run: echo "${{ toJson(job) }}"
      - run: docker volume ls
      - run: |
          docker run --rm \
          --volumes-from ${{ job.services.wordpress }} \
          --network ${{ job.container.network }} \
          -e WORDPRESS_DB_HOST=db:3306 \
          -e WORDPRESS_DB_NAME=wordpress \
          -e WORDPRESS_DB_USER=wordpress \
          -e WORDPRESS_DB_PASSWORD=wordpress \
          wordpress:cli \
          wp core install \
          --path="/var/www/html" \
          --url=wordpress \
          --title="Local Wordpress By Docker" \
          --admin_user=admin \
          --admin_password=admin \
          --admin_email=admin@example.com
      - run: curl wordpress
