name: integration-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cached dependencies
        uses: actions/cache@v2
        id: cached-dependencies
        with:
          path: ./vendor
          # the key will change if composer.lock changes
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/composer.lock') }}

      - name: install dependencies
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        uses: php-actions/composer@v4

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
    services:
      chrome:
        image: selenium/standalone-${{matrix.browser}}:3.141.59
        ports:
          - 4444:4444
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: cached dependencies
        uses: actions/cache@v2
        id: cached-dependencies
        with:
          path: ./vendor
          # the key will change if composer.lock changes
          key: ${{ runner.os }}-dependencies-${{ hashFiles('**/composer.lock') }}

      - name: download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./
      - name: run tests
        run: composer run test-${{matrix.browser}}
