name: integration-tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependencies
        uses: php-actions/composer@v4

      - name: cache build
        uses: actions/cache@v2
        id: build
        with:
          path: ./*
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
  chrome:
    runs-on: ubuntu-latest
    needs: [build]
    services:
      chrome:
        image: selenium/standalone-chrome:3.141.59
        ports:
          - 4444:4444
    steps:
      - name: restore build
        uses: actions/cache@v2
        id: build
        with:
          path: ./*
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: run tests
        run: "composer run test-chrome"
  firefox:
    runs-on: ubuntu-latest
    needs: [build]
    services:
      firefox:
        image: selenium/standalone-firefox:3.141.59
        ports:
          - 4444:4444
    steps:
      - name: restore build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: run tests
        run: "composer run test-firefox"
